"""initial schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-09-22 23:07:57.707769

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_users",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("session_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_users")),
        sa.UniqueConstraint("email", name=op.f("uq_admin_users_email")),
    )
    op.create_table(
        "certifications",
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("in_progress", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z][a-zA-Z0-9_-]{0,63}$'", name=op.f("ck_certifications_slug_format")
        ),
        sa.CheckConstraint(
            "sort_order >= 0", name=op.f("ck_certifications_sort_order_non_negative")
        ),
        sa.PrimaryKeyConstraint("slug", name=op.f("pk_certifications")),
    )
    op.create_table(
        "contact_links",
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("href", sa.Text(), nullable=False),
        sa.Column("display", sa.Text(), nullable=False),
        sa.Column("translations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(translations) = 'object' AND translations ? 'en' AND translations ? 'zh-Hant'",
            name=op.f("ck_contact_links_translations_locales"),
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z][a-zA-Z0-9_-]{0,63}$'", name=op.f("ck_contact_links_slug_format")
        ),
        sa.CheckConstraint(
            "sort_order >= 0", name=op.f("ck_contact_links_sort_order_non_negative")
        ),
        sa.PrimaryKeyConstraint("slug", name=op.f("pk_contact_links")),
    )
    op.create_table(
        "contact_messages",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("ip_hash", sa.Text(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "delivery_status", sa.Text(), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("delivery_error", sa.Text(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "delivery_status IN ('pending', 'sent', 'failed')",
            name=op.f("ck_contact_messages_delivery_status_values"),
        ),
        sa.CheckConstraint(
            "ip_hash IS NULL OR ip_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_contact_messages_ip_hash_format"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_messages")),
    )
    op.create_index(
        "contact_messages_created_at_idx",
        "contact_messages",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "education_entries",
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("school", sa.Text(), nullable=False),
        sa.Column("year", sa.Text(), nullable=False),
        sa.Column("translations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(translations) = 'object' AND translations ? 'en' AND translations ? 'zh-Hant'",
            name=op.f("ck_education_entries_translations_locales"),
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z][a-zA-Z0-9_-]{0,63}$'", name=op.f("ck_education_entries_slug_format")
        ),
        sa.CheckConstraint("year ~ '^\\d{4}$'", name=op.f("ck_education_entries_year_format")),
        sa.CheckConstraint(
            "sort_order >= 0", name=op.f("ck_education_entries_sort_order_non_negative")
        ),
        sa.PrimaryKeyConstraint("slug", name=op.f("pk_education_entries")),
    )
    op.create_table(
        "experience_entries",
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("company", sa.Text(), nullable=False),
        sa.Column("start_month", sa.Text(), nullable=False),
        sa.Column("end_month", sa.Text(), nullable=True),
        sa.Column(
            "tech",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("translations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "end_month IS NULL OR (end_month ~ '^\\d{4}-(0[1-9]|1[0-2])$' AND end_month >= start_month)",
            name=op.f("ck_experience_entries_end_month_format"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(tech) = 'array'", name=op.f("ck_experience_entries_tech_is_array")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(translations) = 'object' AND translations ? 'en' AND translations ? 'zh-Hant'",
            name=op.f("ck_experience_entries_translations_locales"),
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z][a-zA-Z0-9_-]{0,63}$'", name=op.f("ck_experience_entries_slug_format")
        ),
        sa.CheckConstraint(
            "start_month ~ '^\\d{4}-(0[1-9]|1[0-2])$'",
            name=op.f("ck_experience_entries_start_month_format"),
        ),
        sa.CheckConstraint(
            "sort_order >= 0", name=op.f("ck_experience_entries_sort_order_non_negative")
        ),
        sa.PrimaryKeyConstraint("slug", name=op.f("pk_experience_entries")),
    )
    op.create_index(
        "experience_entries_sort_idx", "experience_entries", ["sort_order", "slug"], unique=False
    )
    op.create_table(
        "projects",
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("placeholder", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column(
            "tech",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("translations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT placeholder OR (url IS NULL AND tech = '[]'::jsonb)",
            name=op.f("ck_projects_placeholder_empty"),
        ),
        sa.CheckConstraint("jsonb_typeof(tech) = 'array'", name=op.f("ck_projects_tech_is_array")),
        sa.CheckConstraint(
            "jsonb_typeof(translations) = 'object' AND translations ? 'en' AND translations ? 'zh-Hant'",
            name=op.f("ck_projects_translations_locales"),
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z][a-zA-Z0-9_-]{0,63}$'", name=op.f("ck_projects_slug_format")
        ),
        sa.CheckConstraint("sort_order >= 0", name=op.f("ck_projects_sort_order_non_negative")),
        sa.PrimaryKeyConstraint("slug", name=op.f("pk_projects")),
    )
    op.create_index("projects_sort_idx", "projects", ["sort_order", "slug"], unique=False)
    op.create_table(
        "site_texts",
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("translations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(translations) = 'object' AND translations ? 'en' AND translations ? 'zh-Hant'",
            name=op.f("ck_site_texts_translations_locales"),
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z][a-zA-Z0-9_-]{0,63}$'", name=op.f("ck_site_texts_slug_format")
        ),
        sa.PrimaryKeyConstraint("slug", name=op.f("pk_site_texts")),
    )
    op.create_table(
        "skill_groups",
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "items",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("translations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(items) = 'array'", name=op.f("ck_skill_groups_items_is_array")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(translations) = 'object' AND translations ? 'en' AND translations ? 'zh-Hant'",
            name=op.f("ck_skill_groups_translations_locales"),
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z][a-zA-Z0-9_-]{0,63}$'", name=op.f("ck_skill_groups_slug_format")
        ),
        sa.CheckConstraint("sort_order >= 0", name=op.f("ck_skill_groups_sort_order_non_negative")),
        sa.PrimaryKeyConstraint("slug", name=op.f("pk_skill_groups")),
    )
    op.create_index("skill_groups_sort_idx", "skill_groups", ["sort_order", "slug"], unique=False)
    op.create_table(
        "spoken_languages",
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("translations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(translations) = 'object' AND translations ? 'en' AND translations ? 'zh-Hant'",
            name=op.f("ck_spoken_languages_translations_locales"),
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z][a-zA-Z0-9_-]{0,63}$'", name=op.f("ck_spoken_languages_slug_format")
        ),
        sa.CheckConstraint(
            "sort_order >= 0", name=op.f("ck_spoken_languages_sort_order_non_negative")
        ),
        sa.PrimaryKeyConstraint("slug", name=op.f("pk_spoken_languages")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("spoken_languages")
    op.drop_index("skill_groups_sort_idx", table_name="skill_groups")
    op.drop_table("skill_groups")
    op.drop_table("site_texts")
    op.drop_index("projects_sort_idx", table_name="projects")
    op.drop_table("projects")
    op.drop_index("experience_entries_sort_idx", table_name="experience_entries")
    op.drop_table("experience_entries")
    op.drop_table("education_entries")
    op.drop_index("contact_messages_created_at_idx", table_name="contact_messages")
    op.drop_table("contact_messages")
    op.drop_table("contact_links")
    op.drop_table("certifications")
    op.drop_table("admin_users")
    # ### end Alembic commands ###
