"""tools, archive and credential links

Revision ID: 0005_tools_archive
Revises: 0004_experience_company_url
Create Date: 2026-09-27 02:52:03.990359

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0005_tools_archive"
down_revision: str | None = "0004_experience_company_url"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "archive_entries",
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("month", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("translations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(translations) = 'object' AND translations ? 'en' AND translations ? 'zh-Hant'",
            name=op.f("ck_archive_entries_translations_locales"),
        ),
        sa.CheckConstraint(
            "month ~ '^\\d{4}-(0[1-9]|1[0-2])$'", name=op.f("ck_archive_entries_month_format")
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z][a-zA-Z0-9_-]{0,63}$'", name=op.f("ck_archive_entries_slug_format")
        ),
        sa.CheckConstraint(
            "sort_order >= 0", name=op.f("ck_archive_entries_sort_order_non_negative")
        ),
        sa.PrimaryKeyConstraint("slug", name=op.f("pk_archive_entries")),
    )
    op.create_index(
        "archive_entries_sort_idx", "archive_entries", ["sort_order", "slug"], unique=False
    )
    op.create_table(
        "tools",
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column(
            "tech",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("translations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("jsonb_typeof(tech) = 'array'", name=op.f("ck_tools_tech_is_array")),
        sa.CheckConstraint(
            "jsonb_typeof(translations) = 'object' AND translations ? 'en' AND translations ? 'zh-Hant'",
            name=op.f("ck_tools_translations_locales"),
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z][a-zA-Z0-9_-]{0,63}$'", name=op.f("ck_tools_slug_format")
        ),
        sa.CheckConstraint("sort_order >= 0", name=op.f("ck_tools_sort_order_non_negative")),
        sa.PrimaryKeyConstraint("slug", name=op.f("pk_tools")),
    )
    op.create_index("tools_sort_idx", "tools", ["sort_order", "slug"], unique=False)
    op.add_column("certifications", sa.Column("url", sa.Text(), nullable=True))
    op.add_column("education_entries", sa.Column("url", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("education_entries", "url")
    op.drop_column("certifications", "url")
    op.drop_index("tools_sort_idx", table_name="tools")
    op.drop_table("tools")
    op.drop_index("archive_entries_sort_idx", table_name="archive_entries")
    op.drop_table("archive_entries")
    # ### end Alembic commands ###
